name: thank_you_pro
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  
  
  cupertino_icons: ^1.0.6
  gap:
  responsive_sizer:
  flutter_onboarding_slider: ^1.0.11
  go_router:
  animated_bottom_navigation_bar: ^1.3.0
  carousel_slider:
  shimmer:
  popover: ^0.2.8+2
  pinput: ^3.0.1
  dio:
  flutter_easyloading: ^3.0.5
  flutter_riverpod:
  cached_network_image:
  shared_preferences: ^2.2.2
  image_picker: ^1.0.4
  lottie: ^2.7.0
  flutter_cart:
  confetti: ^0.7.0
  badges: ^3.1.2
  animated_text_kit: ^4.2.2
  flutter_staggered_grid_view: ^0.7.0
  bottom_navy_bar: ^6.0.0
  flutter_lorem: ^2.0.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^8.0.3
  percent_indicator: ^4.2.3
  country_picker:
  fluttertoast:
  logger: ^2.3.0
# drawing tools
  flutter_colorpicker: ^1.0.3
  flutter_hooks: ^0.18.5+1
  flutter_svg: ^2.0.9
  file_saver: ^0.2.9
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  universal_html: ^2.2.4
  file_picker: ^6.1.1
  path_provider:
  circular_reveal_animation: ^2.0.1
  auto_size_text: ^3.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^3.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/icons/
    - assets/images/
    - assets/lottie/

  fonts:
    - family: Sacramento
      fonts:
        - asset: assets/fonts/Sacramento-Regular.ttf
    - family: CormorantGaramond
      fonts:
        - asset: assets/fonts/CormorantGaramond-Regular.ttf
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Outfit-Black.ttf
          weight: 800
        - asset: assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Outfit-Thin.ttf
          weight: 100 
    
       
  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
